### ISSUE TITLE
Cloak cannot be used in the latest version of Android SS

### ISSUE THREAD

**Issue by loyess** [cbeuw/Cloak-android#13]
The log is as follows:
```
06-03 20:31:01.025  6939  7302 E libsslocal: 2020-06-03T20:31:01.023+08:00 INFO  shadowsocks 1.8.12
06-03 20:31:01.046  6939  7302 E libsslocal: 2020-06-03T20:31:01.045+08:00 INFO  started plugin "/data/app/com.github.shadowsocks.plugin.ck_client-RrDoO0hGHK4zycsZImCBbA==/lib/arm64/libck-client.so" on 127.0.0.1:42607 <-> <My_Server-IP>:443 (7317)
06-03 20:31:01.501  6939  7302 E libsslocal: panic: runtime error: index out of range [1] with length 1
06-03 20:31:01.503  6939  7302 E libsslocal: goroutine 1 [running]:
06-03 20:31:01.503  6939  7302 E libsslocal: github.com/cbeuw/Cloak/internal/client.ssvToJson(0x400000a112, 0xdf, 0x6070c89e33, 0x1, 0xd)
06-03 20:31:01.503  6939  7302 E libsslocal: 	C:/Users/cbeuw/StudioProjects/Cloak-android/app/src/.deps/Cloak/internal/client/state.go:89 +0x4e0
06-03 20:31:01.503  6939  7302 E libsslocal: github.com/cbeuw/Cloak/internal/client.ParseConfig(0x400000a112, 0xdf, 0x4, 0x0, 0x0)
06-03 20:31:01.503  6939  7302 E libsslocal: 	C:/Users/cbeuw/StudioProjects/Cloak-android/app/src/.deps/Cloak/internal/client/state.go:107 +0x78
06-03 20:31:01.503  6939  7302 E libsslocal: main.main()
06-03 20:31:01.503  6939  7302 E libsslocal: 	C:/Users/cbeuw/StudioProjects/Cloak-android/app/src/.deps/Cloak/cmd/ck-client/ck-client.go:81 +0x71c
06-03 20:31:11.048  6939  7302 E libsslocal: 2020-06-03T20:31:11.047+08:00 WARN  plugin "/data/app/com.github.shadowsocks.plugin.ck_client-RrDoO0hGHK4zycsZImCBbA==/lib/arm64/libck-client.so" for <My_Server-IP>:443 listening on 127.0.0.1:42607 isn't started yet, elapsed 10.0s
06-03 20:31:11.050  6939  7302 E libsslocal: 2020-06-03T20:31:11.050+08:00 ERROR terminating plugin process 7317, error: No such process (os error 3)
06-03 20:31:11.051  6939  7302 E libsslocal: 2020-06-03T20:31:11.050+08:00 ERROR waitpid(7317) error: No child processes (os error 10)
06-03 20:31:11.056  6939  7302 E libsslocal: 2020-06-03T20:31:11.051+08:00 ERROR one of servers exited unexpectly, result: Err(Custom { kind: Other, error: "plugin exited unexpectedly with exit code: 2" })
06-03 20:31:11.056  6939  7302 E libsslocal: thread 'main' panicked at 'aborted with server exited unexpectly', src/bin/local.rs:310:45
06-03 20:31:11.056  6939  7302 E libsslocal: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Note: Normal use in Android 5.0.6 version

**Comment by qwerttvv** [comment]
![](https://user-images.githubusercontent.com/56712217/82520061-c8b43480-9b55-11ea-9bce-2f715e8d10bf.jpg)

**Comment by cbeuw** [comment]
I tried to reproduce this but couldn't. Could you try to click through each one of the plugin configuration options? It may not have been properly initialised

**Comment by qwerttvv** [comment]
> I tried to reproduce this but couldn't. Could you try to click through each one of the plugin configuration options? It may not have been properly initialised

still not working with click

cloak android v2.2.1 + ss android v5.1.1

**Comment by Stan-Lin-** [comment]
Yep, seems busted.

**Comment by loyess** [comment]
[#2535](https://github.com/shadowsocks/shadowsocks-android/issues/2535)

**Comment by qwerttvv** [comment]
https://github.com/shadowsocks/shadowsocks-android/releases/tag/v5.1.2

ss v5.1.2 + ck v2.2.1 still not working

**Comment by loyess** [comment]
it crashed when parsing config.

**Comment by loyess** [comment]
The reason found： [e39de34](https://github.com/shadowsocks/shadowsocks-rust/commit/e39de3416f2c5cdaaf8ac30a1a5e935228917ec0)

The ";V" parameter added in the plug-in options causes the index to be out of range during Cloak configuration parsing, Shadowsocks-rust has removed this option.

The next time Shadowsocks-android releases the apk, it will be fixed.

If you want to experience the latest version (the last commit) of ss-android apk, you can go to the ss-android project to download the version automatically compiled by Ci.

https://622-7190986-gh.circle-artifacts.com/0/apk/mobile/debug/mobile-universal-debug.apk
